# Numpy for Machine Learning

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.



**Numpy Vs Python Lists:**

- The list can be homogeneous or heterogeneous.
- Element wise operation is not possible on the list.
- Python list is by default 4 dimensional. But we can create an  N-Dimensional list. But then too it will be 4 D list storing another 4D list
- Elements of a list need not be contiguous in memory.

**Numpy**

- consumes less memory.
- fast as compared to the python List.
- convenient to use.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.1'

In [ ]:
# !pip install numpy

In [4]:
# outer dimension -> Inner Dimension
x = np.random.randint(10,size=(3,4,5))
x

array([[[2, 2, 4, 2, 9],
        [8, 4, 4, 8, 0],
        [0, 9, 8, 7, 8],
        [7, 9, 2, 8, 2]],

       [[2, 5, 9, 1, 5],
        [4, 6, 8, 2, 0],
        [9, 1, 1, 2, 4],
        [3, 0, 2, 4, 5]],

       [[3, 2, 9, 7, 0],
        [7, 9, 7, 9, 7],
        [3, 5, 2, 1, 7],
        [0, 4, 1, 3, 2]]])

In [5]:
#ndim (x, y, z) = 3 demensional ... (x,y,z,q) = 4 dimensional
x.ndim

3

In [6]:
x.shape

(3, 4, 5)

In [7]:
# (x * y * z)
x.size 

60

In [8]:
x.dtype

dtype('int64')

In [9]:
# itemsize returns the size (in bytes) of each element of a NumPy array. itemsize will be 8, because this array consists of integers and size of integer (in bytes) is 8 bytes.
x.itemsize # 8 bytes

8

In [10]:
# size * bytes
x.nbytes

480

## Creating Arrays

In [20]:
x = np.array(object=[1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [21]:
type(x)

numpy.ndarray

In [22]:
x.dtype

dtype('int64')

In [24]:
x = np.array(object=[1,2,3,4,5], dtype = complex)
x

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [23]:
x.dtype

dtype('int64')

In [33]:
y = np.array([1,2,3,4,5,6,7])
type(y)
y

array([1, 2, 3, 4, 5, 6, 7])

## Create Array from Scratch

In [35]:
np.zeros(shape=(4,5),dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
np.ones(shape=(3,3), dtype = "float")

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.full(shape=(4,4),fill_value= 3.1456)

array([[3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456],
       [3.1456, 3.1456, 3.1456, 3.1456]])

In [42]:
# Array filled with linear sequence (start, stop, step)
# start value is inclusive
# end value is exclusive
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.arange(1,25,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [44]:
# array with equally spaced data points 
# (start, stop, points)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.random.random((3,3))

array([[3.18210125e-01, 9.06217783e-04, 5.64036753e-01],
       [2.80842734e-02, 4.67497991e-02, 9.80528787e-01],
       [9.51043064e-01, 3.46748206e-01, 4.30013561e-01]])

In [50]:
# Draw random samples from a normal (Gaussian) distribution
# (Loc (center), scale (width), size)
np.random.normal(0,1,(3,3))

array([[ 0.21892788, -0.63943948,  1.40065076],
       [-1.16222907, -0.5288664 , -0.03134052],
       [-1.96183514, -0.94915318, -0.85954024]])

In [6]:
# random integers between 10 & 100
np.random.randint(10,100,size=(2,3))

array([[29, 43, 53],
       [69, 93, 48]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.empty(4)

array([1., 1., 1., 1.])

In [ ]:
## MAKE SURE ALL VALUES ARE SAME DATA TYPE
# bool (true, false)
# int (1)
# complex (Imaginary Numbers)
# float (1.0000)
# object

In [44]:
x = np.random.randint(10,100,(4,3))
x

array([[57, 78, 35],
       [77, 93, 33],
       [67, 24, 33],
       [82, 99, 52]])

In [15]:
# Keep in mind that array starts at 0
x[1,2]

89

In [16]:
x[2,2]

97

In [17]:
x[1,0]

77

In [20]:
x

array([[27, 94, 75],
       [77, 15, 89],
       [19, 79, 97],
       [75, 27, 97]])

In [21]:
x[2]

array([19, 79, 97])

In [22]:
x[-1]

array([75, 27, 97])

In [23]:
x[-2,-1]

97

In [ ]:
# x[start:end:stepsize,start:end:stepsize]

In [30]:
x[1:4]

array([[77, 15, 89],
       [19, 79, 97],
       [75, 27, 97]])

In [31]:
x[1:3]

array([[77, 15, 89],
       [19, 79, 97]])

In [29]:
x[1:3,1:3]

array([[15, 89],
       [79, 97]])

In [61]:
# A seed generates the same random numbers every time (similar to a seed in Minectaft)
# seed only works for np.random functions ran within the same ipynb Code Cell
np.random.seed(6)
y = np.random.randint(0,1000,(7,7))


In [62]:
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 848, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [63]:
y[2:6,2]

array([495, 130, 637, 197])

In [48]:
# [start:stop:step, start:stop:step]
y[1:7:2,1:7:2]

array([[848, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

## Array Slicing as Views

In [64]:
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 848, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [66]:
a = y[1:7:2,1:7:2]
a

array([[848, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [67]:
a[0,0] = 999

In [68]:
a

array([[999, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [69]:
# Original Array is modified (WHO KNEW)
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 999, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [70]:
# Use a copy NOT a view (as previously shown)
a = y[1:7:2,1:7:2].copy()
a

array([[999, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [71]:
a[0,0] = 100

In [72]:
a

array([[100, 281,  75],
       [264, 204, 987],
       [939, 485, 644]])

In [73]:
y

array([[906, 713, 227, 980, 618, 365, 335],
       [362, 999, 318, 281, 513,  75, 333],
       [697,  26, 495, 161, 748, 622, 324],
       [929, 264, 130, 204, 980, 987,  31],
       [450, 901, 637, 410, 527, 473, 342],
       [626, 939, 197, 485, 433, 644, 485],
       [ 62, 592, 194, 127, 322, 319, 147]])

In [74]:
y.shape

(7, 7)

## Array Shape Modification

In [18]:
# Number of elements in the newly shaped array should be equal to the number of elements in the original array
# If elements arent equal you will get an error
np.random.seed(6)
z = np.random.randint(0,100,(5,3))
z

array([[10, 73, 99],
       [84, 79, 80],
       [62, 25,  1],
       [75, 77, 57],
       [26, 33, 68]])

In [76]:
z.reshape(3,5)

array([[10, 73, 99, 84, 79],
       [80, 62, 25,  1, 75],
       [77, 57, 26, 33, 68]])

In [77]:
z.reshape(3,6)

ValueError: cannot reshape array of size 15 into shape (3,6)

In [63]:
z.reshape(3,2)

ValueError: ignored

In [83]:
#concatenate
np.random.seed(0)
a = np.random.randint(0,100,(2,3))
b = np.random.randint(5,500,(2,3))

In [92]:
a

array([[44, 47, 64],
       [67, 67,  9]])

In [89]:
b

array([[216, 282, 247],
       [297,  92,  75]])

In [86]:
# Places arrays on top of each other
np.concatenate([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [216, 282, 247],
       [297,  92,  75]])

In [69]:
# Places arrays next to each other
np.concatenate([a,b],axis=1)

array([[ 44,  47,  64, 216, 282, 247],
       [ 67,  67,   9, 297,  92,  75]])

In [87]:
# Vertical Stack
np.vstack([a,b])

array([[ 44,  47,  64],
       [ 67,  67,   9],
       [216, 282, 247],
       [297,  92,  75]])

In [90]:
# Horisontal Stack
np.hstack([a,b])

## Mathematical Operations on Numpy Arrays

In [4]:
x = np.arange(4)

In [7]:
x

array([0, 1, 2, 3])

In [6]:
x + 5

array([5, 6, 7, 8])

In [8]:
x - 2

array([-2, -1,  0,  1])

In [9]:
x / 2

array([0. , 0.5, 1. , 1.5])

In [10]:
x*2

array([0, 2, 4, 6])

In [13]:
# Flooor Division (returns the largest possible integer)
x // 2

array([0, 0, 1, 1])

In [12]:
x %2

array([0, 1, 0, 1])

In [80]:
x**2

array([0, 1, 4, 9])

In [14]:
np.add(x,2)

array([2, 3, 4, 5])

In [15]:
np.subtract(x,2)

array([-2, -1,  0,  1])

## Boolean Indexing

In [19]:
z

array([[10, 73, 99],
       [84, 79, 80],
       [62, 25,  1],
       [75, 77, 57],
       [26, 33, 68]])

In [20]:
z > 50

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [21]:
z[z > 50]

array([73, 99, 84, 79, 80, 62, 75, 77, 57, 68])

In [22]:
np.exp(z)

array([[2.20264658e+04, 5.05239363e+31, 9.88903032e+42],
       [3.02507732e+36, 2.03828107e+34, 5.54062238e+34],
       [8.43835667e+26, 7.20048993e+10, 2.71828183e+00],
       [3.73324200e+32, 2.75851345e+33, 5.68572000e+24],
       [1.95729609e+11, 2.14643580e+14, 3.40427605e+29]])

In [88]:
np.exp2(z)

array([[1.02400000e+03, 9.44473297e+21, 6.33825300e+29],
       [1.93428131e+25, 6.04462910e+23, 1.20892582e+24],
       [4.61168602e+18, 3.35544320e+07, 2.00000000e+00],
       [3.77789319e+22, 1.51115727e+23, 1.44115188e+17],
       [6.71088640e+07, 8.58993459e+09, 2.95147905e+20]])

In [23]:
np.log(x)

/tmp/ipykernel_2380139/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [24]:
np.sum(z)

849

In [25]:
# Variance
np.var(z)

835.7066666666666

In [92]:
# Standard Deviation
np.std(z)

28.9085915718263

In [26]:
np.std(z,axis=0)

array([28.60489469, 23.40598214, 33.07567082])

In [27]:
np.min(z)

1

In [28]:
np.max(z)

99

In [29]:
# Return the index of the min value
np.argmin(z)

8

In [97]:
# Return the index of the max value
np.argmax(z)

2